theme: minima
title: Replicate THIS!
author: Kelsi West, PhD, MPH
description: How many tutorials/analyses out there I can *actually* replicate? Let's drive progress with clear communication, open code, and shared data.
